name: dashboard_mealz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  get: ^4.6.6
  logger: ^2.5.0
  shared_preferences: ^2.3.4
  uuid: ^4.5.1
  dotted_border: ^2.1.0
  file_picker: ^8.1.6
  flutter_dropzone: ^4.2.1
  font_awesome_flutter: ^10.8.0
  excel: ^4.0.6
  skeleton_text: ^3.0.1
  syncfusion_flutter_xlsio: ^28.1.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
